### ISSUE TITLE
Enable SSL on cuckoo.social instance

### ISSUE THREAD

**Issue by pingu8007** [NanaMorse/Cuckoo.Plus#113]
# Subject

Please enable SSL on [cuckoo.social](http://www.cuckoo.social) instance (to prevent red lock when posting anything)

# Possible solution

1. Hosting with github pages and [enabled SSL for custom domain](https://help.github.com/articles/securing-your-github-pages-site-with-https/)
2. Use npm package [greenlock-express](https://www.npmjs.com/package/greenlock-express)
3. Hosting on server with SSL enabled

**Comment by Ping-timeout** [comment]
~~self-hosted https://plus.timeout.moe~~

**Comment by NanaMorse** [comment]
> > 1. Hosting on server with SSL enabled
> 
> self-hosted https://plus.timeout.moe

nice

**Comment by NanaMorse** [comment]
done
