### ISSUE TITLE
Font wrong in MAC

### ISSUE THREAD

**Issue by kirinrin** [NanaMorse/Cuckoo.Plus#165]
Font wrong in left and top right nav bar

Mac 10.14.3 safari 12.0.3 2K+ Resolution

![屏幕快照 2019-03-25 上午10 26 25](https://user-images.githubusercontent.com/2627788/54891492-85761b80-4ee8-11e9-803a-23cb012839e2.png)
![屏幕快照 2019-03-25 上午10 26 16](https://user-images.githubusercontent.com/2627788/54891493-85761b80-4ee8-11e9-860f-923c01e1fd61.png)

**Comment by NanaMorse** [comment]
It would happen while material icon CDN source loading failed, and could be solved by refreshing your browser usually.
If still not working, please check your internet accessibility, make sure that the GFW won't block the CDN site.
