### ISSUE TITLE
experimental link preview function

### ISSUE THREAD

**Issue by NanaMorse** [NanaMorse/Cuckoo.Plus#190]

**Comment by aka-rin** [comment]
For instances running Mastodon v2.6.0 or later versions, they have a preview card object in a status with a link preview: `https://docs.joinmastodon.org/api/entities/#status`.

For instances running older versions, you can use `/api/v1/statuses/:id/card` or Misskey API: `https://misskey.io/url?url=https%3A%2F%2Fcuckoo.social`.

**Comment by NanaMorse** [comment]
> For instances running Mastodon v2.6.0 or later versions, they have a preview card object in a status with a link preview: `https://docs.joinmastodon.org/api/entities/#status`.
> 
> For instances running older versions, you can use `/api/v1/statuses/:id/card` or Misskey API: `https://misskey.io/url?url=https%3A%2F%2Fcuckoo.social`.

I see, maybe this issue's title is too simple to make visitors understand clearly, actually the "preview" here means the preview image and text content for a specific link which is included in a status content, not the preview for a status card.
