### ISSUE TITLE
Official WebApp Is Down :(

### ISSUE THREAD

**Issue by SonaliBendre** [NanaMorse/Cuckoo.Plus#236]
https://upload.vaa.red/2dQUYN#5f5b03abb9da17c5c35150fca5e279c8

**Comment by SonaliBendre** [comment]
![image](https://user-images.githubusercontent.com/73757361/122542929-e00b6d00-d048-11eb-8f97-9ea0aea77555.png)

**Comment by NanaMorse** [comment]
oh wtf I'll repair it asap

**Comment by NanaMorse** [comment]
fixed

**Comment by SonaliBendre** [comment]
Nice Thanks
