### ISSUE TITLE
cuckoo.social ssl cert expired

### ISSUE THREAD

**Issue by fhoshino** [NanaMorse/Cuckoo.Plus#239]
![brave_2022-06-29_22-26-55](https://user-images.githubusercontent.com/771955/176462141-c7fe3cb7-fcdd-492c-911d-e9bce30298d7.png)

**Comment by NanaMorse** [comment]
修了

好奇怪啊，明明我买了五年有效期的证书，为啥每过一年都要重新设置一次

**Comment by wakest** [comment]
looks like its expired again
