### ISSUE TITLE
Show Repost content, enable repost action

### ISSUE THREAD

**Issue by NanaMorse** [NanaMorse/Cuckoo.Plus#40]

**Comment by NanaMorse** [comment]
repost与unrepost的逻辑如何在类G+的UI下实现，这个需要考虑一下

**Comment by NanaMorse** [comment]
原来自己repost别人的status，在自己的timeline里是看不见的
我有点儿慌

**Comment by roytam1** [comment]
> 原来自己repost别人的status，在自己的timeline里是看不见的

對，只會flag該post的 `reblogged`
