### ISSUE TITLE
Some post content overflow

### ISSUE THREAD

**Issue by SLAPaper** [NanaMorse/Cuckoo.Plus#42]
Screenshot:
![chrome_2018-10-21_00-20-14](https://user-images.githubusercontent.com/7543632/47257961-4a019c00-d4c7-11e8-8d3c-ac37e0d7be7f.png)

Corresponding DOM:
![chrome_2018-10-21_00-22-32](https://user-images.githubusercontent.com/7543632/47257973-73222c80-d4c7-11e8-9795-311e15dc0afe.png)

**Comment by KTachibanaM** [comment]
<del>bug被发现了</del>

**Comment by KTachibanaM** [comment]
并不是删除线的锅 pixiv fork的mastodon擅自返回了invisible和ellipsis这两个我们的前端不存在的css class 2333
