### ISSUE TITLE
Stop auto loading new post when timeline is not scrolled to top

### ISSUE THREAD

**Issue by fhoshino** [NanaMorse/Cuckoo.Plus#81]
Stop auto loading new post to feed when timeline is not scrolled to top, making posts shift when reading, resume auto loading when timeline is scrolled back to top

**Comment by HerringtonDarkholme** [comment]
What if a user is reading the topmost post? It would be desirable to pause auto loading as well.

Maybe we can conceive a more exquisite way to construe user behavior as "reading now".

**Comment by NanaMorse** [comment]
what about using new post notice button, like Google Plus?

**Comment by NanaMorse** [comment]
How about this, there will be a option for users to select the way of real-time new post's display, the way like G+ for normal usage, and the real-time-load way for the special days like New Year's Day.
